# **Tensors:-**
     Tensors are the data stucture.The work that array done in 1D the ame work tensore does in N-D.

# **0-Dimension Tensor: (scalar)**
           a single number
***Example:-***  after a forward pass it computes a single scalar value indicating the difference between the predicted and actual outputs.
           
# **1-Dimension Tensor: (vector)**
           arrays
           a single number
***Example:-***  in NLP each word in a sentence may be represented as a 1D vector using embeddings.

# **2-Dimension Tensor: (matrices)**
           gray scale images
           
# **3-Dimension Tensor:**
           RGB image
           width x height x channel

# **4-Dimension Tensor:**
           Batches of RGB images
           one video
           batch size x width x height x channel

# **5-Dimension Tensor:**
           video data
           no of videos x no of frames x width x height x channel

# **Why are tensors useful?**


1.   You can easily perform mathematical operations (addition, muliplication, dot product) necessary for neural network operations.
2.   Data like audio,videos,images,text can be easily represented in tensors.

1.   Tensors can run on GPUs and can perfrm many operations parallely and can boost the speed of operations.






In [2]:
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
  print("GPU not available,Using CPU.")

GPU is available
Using GPU:Tesla T4


# **Creating Tensor**

In [ ]:
# using empty
a=torch.empty(2,3)

In [ ]:
# check type
a.type

<function Tensor.type>

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.5642, 0.5810, 0.9594],
        [0.2471, 0.2335, 0.5658]])

In [ ]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways
# arange
print("using arange: ",torch.arange(0,10,2))

# using linspace
print("using linspace: ",torch.linspace(0,10,10))

# using eye
print("using eye: ",torch.eye(5))

# using full
print("using full: ",torch.full((3,3),5))

using arange:  tensor([0, 2, 4, 6, 8])
using linspace:  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye:  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full:  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# **Tensor Shapes**

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[7959390389040738153, 2459014003229860468, 8104338990068757365],
        [8317708060499076466, 2459014313992534562, 2478212826149773680]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.5512, 0.3322, 0.4907],
        [0.4198, 0.7865, 0.0894]])

# **Tensor Data Types**

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

# **Mathematical Operation**



# 1.   **Scalar Operation**



In [ ]:
x=torch.rand(2,2)
x

tensor([[0.7641, 0.2237],
        [0.2583, 0.5881]])

In [ ]:
# addition
x+2

# Subtraction
x-2

# Multiplication
x*3

# division
x/3

# int division
(x*100)//3

# mod
((x*100)//3)%2

# power
x**2

tensor([[0.5838, 0.0500],
        [0.0667, 0.3459]])


# 2.   **Element wise operation**



In [19]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.8921, 0.1264, 0.1395],
        [0.5217, 0.7545, 0.2167]])
tensor([[0.4805, 0.8892, 0.7144],
        [0.0646, 0.9799, 0.5265]])


In [21]:
# add
a+b
# sub
a-b
# multiplication
a*b
# division
a/b
# power
a**b
# mod
a % b

tensor([[0.4116, 0.1264, 0.1395],
        [0.0050, 0.7545, 0.2167]])

In [22]:
c= torch.tensor([1,-2,3,-4])

In [23]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [24]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [25]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [26]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [27]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [28]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [29]:
# clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])



# **3.   Reduction Operation**



In [9]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[6., 8., 6.],
        [6., 8., 3.]])

In [10]:
# sum
e.sum()

tensor(37.)

In [11]:
# sum along columns
torch.sum(e,dim=0)

tensor([12., 16.,  9.])

In [12]:
# sum along rows
torch.sum(e,dim=1)

tensor([20., 17.])

In [13]:
# mean
torch.mean(e)

tensor(6.1667)

In [14]:
# mean along columns
torch.mean(e,dim=0)

tensor([6.0000, 8.0000, 4.5000])

In [15]:
# meadian
torch.median(e)

tensor(6.)

In [16]:
# max and min
torch.max(e)
torch.min(e)

tensor(3.)

In [17]:
# product
torch.prod(e)

tensor(41472.)

In [18]:
# standard deviation
torch.std(e)

tensor(1.8348)

In [19]:
# variance
torch.var(e)

tensor(3.3667)

In [20]:
# argmax
torch.argmax(e)

tensor(1)

In [21]:
# argmin
torch.argmin(e)

tensor(5)



# **4.   Matrix Operation**



In [22]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[7, 6, 4],
        [9, 8, 2]])
tensor([[6, 4],
        [5, 8],
        [6, 7]])


In [23]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 96, 104],
        [106, 114]])

In [24]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])
# dot multiplication
torch.dot(vector1,vector2)

tensor(11)

In [26]:
# transpose
torch.transpose(f,0,1)

tensor([[7, 9],
        [6, 8],
        [4, 2]])

In [29]:
h=torch.randint(size=(3,3),dtype=torch.float32,low=0,high=10)
h

tensor([[5., 6., 9.],
        [9., 8., 4.],
        [2., 5., 1.]])

In [30]:
# determinant
torch.det(h)

tensor(195.0000)

In [32]:
# inverse
torch.inverse(h)

tensor([[-0.0615,  0.2000, -0.2462],
        [-0.0051, -0.0667,  0.3128],
        [ 0.1487, -0.0667, -0.0718]])



# **5.   Comparision Operation**



In [33]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[6, 2, 7],
        [9, 5, 3]])
tensor([[3, 2, 8],
        [4, 8, 8]])


In [34]:
# greater than
i>j

tensor([[ True, False, False],
        [ True, False, False]])

In [35]:
# less than
i<j

tensor([[False, False,  True],
        [False,  True,  True]])

In [36]:
# equal to
i==j

tensor([[False,  True, False],
        [False, False, False]])

In [37]:
# not equal to
i != j

tensor([[ True, False,  True],
        [ True,  True,  True]])

In [38]:
# greater than or eual to
i >= j

tensor([[ True,  True, False],
        [ True, False, False]])

In [39]:
# less than or equal to
i <= j

tensor([[False,  True,  True],
        [False,  True,  True]])



# **6.   Special Operation**



In [40]:
k=torch.randint(size=(2,3),low=0,high=10)
k

tensor([[7, 5, 3],
        [3, 8, 1]])

In [41]:
# log
torch.log(k)

tensor([[1.9459, 1.6094, 1.0986],
        [1.0986, 2.0794, 0.0000]])

In [42]:
# exp
torch.exp(k)

tensor([[1.0966e+03, 1.4841e+02, 2.0086e+01],
        [2.0086e+01, 2.9810e+03, 2.7183e+00]])

In [43]:
# sqrt
torch.sqrt(k)

tensor([[2.6458, 2.2361, 1.7321],
        [1.7321, 2.8284, 1.0000]])

In [44]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9991, 0.9933, 0.9526],
        [0.9526, 0.9997, 0.7311]])

In [46]:
# softmax
torch.softmax(e,dim=0)

tensor([[0.5000, 0.5000, 0.9526],
        [0.5000, 0.5000, 0.0474]])

In [47]:
# relu
torch.relu(k)

tensor([[7, 5, 3],
        [3, 8, 1]])

# Inplace Operation

In [3]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.2196, 0.7982, 0.1887],
        [0.5484, 0.0348, 0.0898]])
tensor([[0.2697, 0.3068, 0.5337],
        [0.0474, 0.3896, 0.9136]])


In [4]:
m.add_(n)

tensor([[0.4894, 1.1050, 0.7225],
        [0.5959, 0.4244, 1.0033]])

In [5]:
m

tensor([[0.4894, 1.1050, 0.7225],
        [0.5959, 0.4244, 1.0033]])

In [6]:
n

tensor([[0.2697, 0.3068, 0.5337],
        [0.0474, 0.3896, 0.9136]])

In [7]:
m.relu_()

tensor([[0.4894, 1.1050, 0.7225],
        [0.5959, 0.4244, 1.0033]])

In [8]:
m

tensor([[0.4894, 1.1050, 0.7225],
        [0.5959, 0.4244, 1.0033]])

# Copying a tensor

In [10]:
a=torch.rand(size=(2,3))
a

tensor([[0.0828, 0.0917, 0.1403],
        [0.3376, 0.5896, 0.0347]])

In [11]:
b=a

In [12]:
a[0][0]=0

In [13]:
a

tensor([[0.0000, 0.0917, 0.1403],
        [0.3376, 0.5896, 0.0347]])

In [14]:
b

tensor([[0.0000, 0.0917, 0.1403],
        [0.3376, 0.5896, 0.0347]])

In [15]:
id(a)

140111076117792

In [16]:
id(b)

140111076117792

In [17]:
b=a.clone()

In [18]:
a[0][0]=100

In [19]:
a

tensor([[1.0000e+02, 9.1736e-02, 1.4026e-01],
        [3.3765e-01, 5.8960e-01, 3.4662e-02]])

In [20]:
b

tensor([[0.0000, 0.0917, 0.1403],
        [0.3376, 0.5896, 0.0347]])

In [21]:
id(a)

140111076117792

In [22]:
id(b)

140110734310080

# **Tensor operation On GPU**

In [23]:
torch.cuda.is_available()

True

In [24]:
device=torch.device('cuda')

In [25]:
# creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.4342, 0.2622, 0.4735],
        [0.9272, 0.1347, 0.2262]], device='cuda:0')

In [28]:
# moving an existing tensor to GPU
b=a.to(device)

In [29]:
b+5

tensor([[105.0000,   5.0917,   5.1403],
        [  5.3376,   5.5896,   5.0347]], device='cuda:0')

# **Reshaping Tensors**

In [30]:
a=torch.ones((4,4))
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [34]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
b=torch.rand(2,3,4)
b

tensor([[[0.9924, 0.0102, 0.3328, 0.8153],
         [0.4407, 0.3894, 0.5933, 0.3954],
         [0.0408, 0.5066, 0.4636, 0.9807]],

        [[0.4554, 0.6734, 0.9922, 0.8759],
         [0.6750, 0.6624, 0.1194, 0.4993],
         [0.2902, 0.8181, 0.6163, 0.0627]]])

In [36]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [38]:
# unsqueeze ----> add a new dimension at a given position
c=torch.rand(226,226,3)
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [42]:
# squeeze -----> opposite of unsqueeze
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# **Numpy and Pytorch**

In [43]:
import numpy as np

In [44]:
s=torch.tensor([1,2,3])
s

tensor([1, 2, 3])

In [45]:
q=s.numpy()

In [46]:
q

array([1, 2, 3])

In [47]:
type(q)

numpy.ndarray

In [48]:
q=np.array([1,2,3])

In [49]:
type(q)

numpy.ndarray

In [50]:
s=torch.from_numpy(q)

In [51]:
type(s)

torch.Tensor